# Generated by Django 2.0.3 on 2018-03-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='is_assigned_password',
            field=models.BooleanField(default=False),
        ),
    ]
