# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180305_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialsession',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
