# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-08 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion', models.CharField(choices=[('1', '通过'), ('2', '修改'), ('3', '拒绝')], max_length=64, verbose_name='初步结论')),
                ('proposal', models.TextField(max_length=1024, verbose_name='建议')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='分派时间')),
                ('finish_time', models.DateField(verbose_name='审核结束时间')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=60)),
                ('title', models.CharField(max_length=128)),
                ('content', models.FileField(upload_to='thesis/')),
                ('status', models.CharField(choices=[('0', '未分配'), ('1', '审核中'), ('2', '通过'), ('3', '修改'), ('4', '拒绝')], default='0', max_length=64, verbose_name='论文状态')),
                ('keywords', models.CharField(max_length=64, verbose_name='关键词')),
                ('abstract', models.TextField(max_length=256, verbose_name='概述')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('publish_time', models.DateField(verbose_name='发布时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_author', to=settings.AUTH_USER_MODEL)),
                ('handle_memebers', models.ManyToManyField(through='thesis.Review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='review',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesis.Thesis'),
        ),
    ]
