# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-23 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='status',
            field=models.CharField(choices=[(0, '未分配'), (1, '审核中'), (2, '通过'), (3, '修改'), (4, '拒绝')], default=0, max_length=64, verbose_name='论文状态'),
        ),
    ]
