# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-23 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0004_auto_20180223_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='conclusion',
            field=models.CharField(choices=[(1, '通过'), (2, '修改'), (3, '拒绝')], max_length=64, verbose_name='初步结论'),
        ),
        migrations.AlterField(
            model_name='review',
            name='finish_time',
            field=models.DateField(null=True, verbose_name='审核结束时间'),
        ),
    ]
