# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-24 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0005_auto_20180223_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='conclusion',
            field=models.CharField(choices=[(1, '通过'), (2, '修改'), (3, '拒绝')], max_length=64, null=True, verbose_name='初步结论'),
        ),
        migrations.AlterField(
            model_name='review',
            name='proposal',
            field=models.TextField(max_length=1024, null=True, verbose_name='建议'),
        ),
    ]
