# Generated by Django 2.0 on 2018-03-10 13:36

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericTagContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200, unique=True, verbose_name='标题')),
                ('status', models.CharField(choices=[('d', '草稿'), ('p', '发表')], default='p', max_length=1, verbose_name='文章状态')),
                ('body', DjangoUeditor.models.UEditorField(default='', verbose_name='正文')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'ordering': ['last_mod_time'],
                'get_latest_by': 'created_time',
                'verbose_name_plural': '文章',
                'verbose_name': '文章',
            },
        ),
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=200, unique=True, verbose_name='标题')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('rank', models.IntegerField(default=0, verbose_name='排序')),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SideBar', verbose_name='父级分类')),
            ],
            options={
                'ordering': ['rank'],
                'verbose_name_plural': '分类',
                'verbose_name': '分类',
            },
        ),
        migrations.AddField(
            model_name='generictagcontent',
            name='sidebar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SideBar', verbose_name='分类'),
        ),
    ]
