# Generated by Django 2.0.3 on 2018-03-18 08:19

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericTagContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='title')),
                ('body', DjangoUeditor.models.UEditorField(default='', verbose_name='content')),
            ],
            options={
                'verbose_name': 'Tag Content',
            },
        ),
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=200, unique=True, verbose_name='Tag Name')),
                ('rank', models.IntegerField(default=0)),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SideBar', verbose_name='parent node')),
            ],
            options={
                'verbose_name': 'SideBar Tag',
                'ordering': ['rank'],
            },
        ),
        migrations.AddField(
            model_name='generictagcontent',
            name='sidebar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SideBar', verbose_name='tag name'),
        ),
    ]
