# Generated by Django 2.0.3 on 2018-03-15 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generictagcontent',
            options={'verbose_name': 'Tag Content'},
        ),
        migrations.AlterModelOptions(
            name='sidebar',
            options={'ordering': ['rank'], 'verbose_name': '分类'},
        ),
        migrations.RenameField(
            model_name='generictagcontent',
            old_name='theme',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='generictagcontent',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='generictagcontent',
            name='last_mod_time',
        ),
        migrations.RemoveField(
            model_name='generictagcontent',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sidebar',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='sidebar',
            name='last_mod_time',
        ),
        migrations.AlterField(
            model_name='generictagcontent',
            name='sidebar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SideBar', verbose_name='tag name'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='node_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Tag Name'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
