# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-24 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activflow', '0001_initial'),
        ('thesisReview', '0002_auto_20180123_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='activflow.Task'),
        ),
    ]
