# Generated by Django 2.0 on 2018-03-10 13:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'unassign'), ('1', 'underreview'), ('2', 'accpet'), ('3', 'revision'), ('4', 'reject'), ('5', 'waitingverdict')], default='0', max_length=16)),
                ('proposal_to_author', models.TextField(max_length=1024, null=True)),
            ],
            options={
                'permissions': (('view_assignment', 'View Assignment'), ('create_assignment', 'Create Assignment')),
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('organization', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('abstract', models.TextField(max_length=1024)),
                ('file', models.FileField(upload_to='thesis/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('version', models.IntegerField(default=1)),
                ('serial_number', models.UUIDField(default=uuid.uuid4)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('publish_time', models.DateField(auto_now=True)),
            ],
            options={
                'permissions': (('view_paper', 'View Paper'), ('create_paper', 'Create Paper'), ('update_paper', 'Update Paper')),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommandation', models.CharField(choices=[('1', 'accpet'), ('2', 'revision'), ('3', 'reject')], max_length=16)),
                ('confidentia_proposal_to_editor', models.TextField(max_length=1024, null=True)),
                ('proposal_to_author', models.TextField(blank=True, max_length=1024, null=True)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('finish_time', models.DateField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaperReview.Assignment')),
            ],
            options={
                'permissions': (('view_review', 'View Review'), ('create_review', 'Create Review')),
            },
        ),
    ]
