# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 07:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'unassign'), ('1', 'underreview'), ('2', 'accpet'), ('3', 'revision'), ('4', 'reject')], default='0', max_length=16)),
                ('proposal_to_author', models.TextField(max_length=1024)),
            ],
            options={
                'permissions': (('view_assignment', 'View Assignment'), ('create_assignment', 'Create Assignment')),
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('organization', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='thesis/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('abstract', models.TextField(max_length=1024)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('publish_time', models.DateField(auto_now=True)),
            ],
            options={
                'permissions': (('view_paper', 'View Paper'), ('create_paper', 'Create Paper'), ('update_paper', 'Update Paper')),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommandation', models.CharField(choices=[('1', 'accpet'), ('2', 'revision'), ('3', 'reject')], max_length=16)),
                ('confidentia_proposal_to_editor', models.TextField(max_length=1024)),
                ('proposal_to_author', models.TextField(max_length=1024)),
                ('creat_time', models.DateField(auto_now_add=True)),
                ('finish_time', models.DateField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaperReview.Assignment')),
            ],
            options={
                'permissions': (('view_assignment', 'View Assignment'), ('create_assignment', 'Create Assignment')),
            },
        ),
    ]
