# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PaperReview', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='scholar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paper',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.SpecialSession'),
        ),
        migrations.AddField(
            model_name='paper',
            name='uploader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='keywords',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaperReview.Paper'),
        ),
        migrations.AddField(
            model_name='content',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaperReview.Paper'),
        ),
        migrations.AddField(
            model_name='author',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaperReview.Paper'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaperReview.Paper'),
        ),
    ]
