# Generated by Django 2.0 on 2018-03-10 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('PaperReview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paper',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.SpecialSession'),
        ),
        migrations.AddField(
            model_name='paper',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='keywords',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PaperReview.Paper'),
        ),
        migrations.AddField(
            model_name='author',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PaperReview.Paper'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='paper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PaperReview.Paper'),
        ),
    ]
