# Generated by Django 2.0.3 on 2018-03-19 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperReview', '0002_auto_20180318_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='keyword',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='paper',
            name='copyright',
            field=models.FileField(max_length=51200, upload_to='copyright/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Copyright'),
        ),
    ]
