# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 07:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaperReview', '0003_auto_20180305_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
