# Generated by Django 2.0.3 on 2018-03-21 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperReview', '0003_auto_20180321_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='copyright',
            field=models.FileField(max_length=400, upload_to='copyright/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Copyright'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.FileField(max_length=400, upload_to='thesis/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Paper Resource'),
        ),
    ]
