# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 08:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaperReview', '0004_auto_20180305_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='paper',
        ),
        migrations.AddField(
            model_name='paper',
            name='file',
            field=models.FileField(null=True, upload_to='thesis/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='paper',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PaperReview.Paper', unique=True),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
