# Generated by Django 2.0.3 on 2018-03-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperReview', '0004_auto_20180319_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_assigned_password',
            field=models.BooleanField(default=0),
        ),
    ]
