# Generated by Django 2.0.3 on 2018-03-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaperReview', '0005_paper_is_assigned_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='is_assigned_password',
        ),
    ]
