# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaperReview', '0005_auto_20180305_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='paper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PaperReview.Paper'),
        ),
    ]
