# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperReview', '0007_auto_20180305_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='confidentia_proposal_to_editor',
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='proposal_to_author',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
