# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaperReview', '0008_auto_20180305_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PaperReview.Paper'),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='keyword',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PaperReview.Paper'),
        ),
    ]
