# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperReview', '0009_auto_20180305_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='proposal_to_author',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
