# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PaperReview', '0014_auto_20180306_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='serial_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=128, null=True),
        ),
    ]
