# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperReview', '0015_auto_20180306_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='serial_number',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
