# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaperReview', '0017_auto_20180306_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='scholar',
            new_name='reviewer',
        ),
    ]
