# Generated by Django 2.0 on 2018-03-07 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaperReview', '0021_auto_20180307_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': (('view_review', 'View Review'), ('create_review', 'Create Review'))},
        ),
    ]
