# Generated by Django 2.0 on 2018-03-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperReview', '0022_auto_20180307_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('0', 'unassign'), ('1', 'underreview'), ('2', 'accpet'), ('3', 'revision'), ('4', 'reject'), ('5', 'waitingverdict')], default='0', max_length=16),
        ),
    ]
